### ISSUE TITLE
Joia

### ISSUE THREAD

**Issue by gbnera** [HelenDeunerFerreira/myVersionFreeway#1]
Gostei do jogo

**Comment by HelenDeunerFerreira** [comment]
oi, tudo bem?
agradeço por ter gostado do jogo.
também vi que você editou o que escreveu, mas consegui ver a mensagem inteira, não se preocupe. por favor, diga a ele que não estou interessada e não venha no meu perfil tratar desses assuntos pessoais, visto que é uma ferramenta de trabalho.

**Comment by HelenDeunerFerreira** [comment]
> Gostei do jogo

oi, tudo bem?
agradeço por ter gostado do jogo.
também vi que você editou o que escreveu, mas consegui ver a mensagem inteira, não se preocupe. por favor, diga a ele que não estou interessada e não venha no meu perfil tratar desses assuntos pessoais, visto que é uma ferramenta de trabalho.

**Comment by gbnera** [comment]
Opa, não sabia que dava pra ver o edit, eu ia fazer uma pegadinha nele e ele nem sabe mas ai desisti por isso editei. Desculpa por mandar aqui, pode excluir o post
